name: covid19
channels:
  - conda-forge
dependencies:
  - descartes=1.1.0
  - lxml=4.6.3
  - matplotlib=3.1.3
  - pandas=1.2.4
  - pip=20.0
  - python=3.7.6
  - geopandas=0.10.2
  - shapely=1.8.2
  - fiona=1.8.21
  - python-levenshtein=0.12.2
  - seaborn=0.11.1
  - tabulate=0.8.9
  - urllib3=1.26.4
  - pycountry==20.7.3
  - pip:
    - git+https://github.com/manubot/manubot@a57ccf0be6972329ff3010eaaa0c5df7ccebb2d5
    - wget==3.2
    - bs4==0.0.1
    - html5lib==1.1
    - fuzzywuzzy==0.18.0
    - plydata=0.4.3
