name: covid19
channels:
  - conda-forge
dependencies:
  - matplotlib=3.1.3
  - pandas=1.0.3
  - pip=20.0
  - python=3.7.6
  - pip:
    - git+https://github.com/manubot/manubot@a57ccf0be6972329ff3010eaaa0c5df7ccebb2d5
